runtime: python
env: flex

# We are familiar with this
#entrypoint: python main.py

# In production you would use this
entrypoint: gunicorn -b :$PORT secondapp:supercoolapp


runtime_config:
  python_version: 3
